name: Testing
on: [push]
jobs:
  test-ports4u:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.17.7'
      - name: Run build
        run: make
      - name: Upload build
        uses: actions/upload-artifact@v2
        with:
          name: upload-build
          path: |
            ./bdmultiplex